version: '3.7'
services:
  web:
    build: .
    command: streamlit run app.py --server.headless true --browser.serverAddress="0.0.0.0" --server.enableCORS false --browser.gatherUsageStats false --server.fileWatcherType none
    ports:
      - 8501:8501
