version: '3.7'
services:
  web:
    build: .
    command: streamlit run app.py --server.headless true --browser.serverAddress="0.0.0.0" --server.enableCORS false --browser.gatherUsageStats false
    ports:
      - 8000:8000
